### ISSUE TITLE
I have some questions about Tailwind css.

### ISSUE THREAD

**Issue by JangCool** [kenhyuwa/litepie-datepicker#13]
1.Do I need to download all the Tailwind CSS to display this plugin UI properly?

2.Don't you provide a small version of CSS to express the calendar UI?

It is burdensome to use in projects that do not use Tailwind CSS.

Plug-in is so good and I want to use it. Thank you for providing this plug-in.

**Comment by kenhyuwa** [comment]
1. yes, you can download or via cdn of the Tailwind CSS. but,  not work properly. you must override of the class litepie-* for better style of Litepie Datepicker.
2. I not sure, because Litepie Datepicker fully customize color palette system. so be better with Tailwind CSS configuration.

**Comment by JangCool** [comment]
@kenhyuwa Okay. Thank you for your answer. I think it would be good if you could support the small version of Css from now on.

**Comment by kenhyuwa** [comment]
My be, i can release compact version for support pure CSS and Vue 2.*

**Comment by JangCool** [comment]
@kenhyuwa i want compact version Vue3. lol ;)
