### ISSUE TITLE
Uncaught ReferenceError: start is not defined

### ISSUE THREAD

**Issue by alesf** [kenhyuwa/litepie-datepicker#15]
I came upon this error today:
`Uncaught ReferenceError: start is not defined`

On this line:
https://github.com/kenhyuwa/litepie-datepicker/blob/655bced86ba05787389d20fce20186fe28dd7cf8/src/litepie-datepicker.vue#L747

I think this is missing on the line before:
const [start, end] = Object.keys(props.modelValue);

**Comment by alesf** [comment]
I guess this line is also problematic for the same reason:

https://github.com/kenhyuwa/litepie-datepicker/blob/655bced86ba05787389d20fce20186fe28dd7cf8/src/litepie-datepicker.vue#L771

**Comment by kenhyuwa** [comment]
Fix on ([v1.0.14](https://github.com/kenhyuwa/litepie-datepicker/releases/tag/v1.0.14)).
Thank you.
