### ISSUE TITLE
Shortcuts for single?

### ISSUE THREAD

**Issue by radoslawkoziol** [kenhyuwa/litepie-datepicker#17]
We can't we have shortcuts working together with `as-single`? I'd like to use a button, for example "7 days ahead" which selects  7 days from now, on single.

**Comment by kenhyuwa** [comment]
Yes, you can't using shortcut with single datepicker.

**Comment by radoslawkoziol** [comment]
That was rather a suggestion or a question. Do  you plan to implement this? It shouldn't be too difficult. Would be perfect too,  to  give a possibility to change those shortcuts.

**Comment by kenhyuwa** [comment]
Thanks for suggestion, But this feature can't be resolve for now.
