### ISSUE TITLE
tailwind is `base` utility is creating conflicts in existing project. 

### ISSUE THREAD

**Issue by rut2** [kenhyuwa/litepie-datepicker#18]
As litepie-datepicker is rely on tailwind, after successful integration of tailwind, it's conflicting with existing CSS that causes lots of design issues.

How can I integrate litepie without affecting existing design?

**Comment by kenhyuwa** [comment]
Tailwind CSS version?
what's `classes` with conflicting your CSS?

**Comment by rut2** [comment]
@kenhyuwa I am using 
`
"tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.4",
"@tailwindcss/postcss7-compat": "^2.0.4"
`

it's affecting all base tags like `<h1> <h2> ...` and font style as well. 

this is my `_date-picker.scss `

`
//
// _date-picker.scss
//

// tailwind
@tailwind base;
@tailwind components;
@tailwind utilities;

`

**Comment by kenhyuwa** [comment]
in this production or development?

**Comment by rut2** [comment]
It's in development. If I don't use `@tailwind base;` then everything works fine except litepie

**Comment by kenhyuwa** [comment]
can you share tailwind.config.js

**Comment by rut2** [comment]
here it is 

```

const path = require("path");
const colors = require("tailwindcss/colors");

module.exports = {
  important: "#tailwind",
  purge: [path.resolve(__dirname, "./node_modules/litepie-datepicker/**/*.js")],
  theme: {
    extend: {
      colors: {
        // Change with you want it
        "litepie-primary": colors.lightBlue, // color system for light mode
        "litepie-secondary": colors.coolGray // color system for dark mode
      }
    }
  },
  variants: {
    extend: {
      cursor: ["disabled"],
      textOpacity: ["disabled"],
      textColor: ["disabled"]
    }
  }
};

```

**Comment by kenhyuwa** [comment]
do you use vue-cli/vite?
try with `purge: false`.

**Comment by rut2** [comment]
No, we are using basic [vue-cli](https://cli.vuejs.org/guide/) 

Also `purge: false` is not working. [Prefixing](https://tailwindcss.com/docs/configuration#prefix) CSS class name might be the possible solution

**Comment by kenhyuwa** [comment]
so, are your problem is fix now?

**Comment by rut2** [comment]
No actually, as litepie is not using any prefix, CSS classing is not working if I add prefix project. Still the problem is not resolved

**Comment by kenhyuwa** [comment]
I'm not sure with your problem.
because, I also implement to existing project and still work.

**Comment by kenhyuwa** [comment]
please, reopen with spesific issues.
