### ISSUE TITLE
Support for multiple langues

### ISSUE THREAD

**Issue by afunnydev** [kenhyuwa/litepie-datepicker#2]
First of all, great work! Love that you use Tailwind and support Vue 3.

I saw in the props that you planned i18n support in the next major release. Do you know approximately when would that be? Would you be open to accept a PR for i18n support sooner than next major version if I submit one?

**Comment by kenhyuwa** [comment]
Yes, I plan for i18n from day.js locale for next major release.
currently just focus for fix issues and make stable version.
You can submit PR for this feature, I very help full.

**Comment by afunnydev** [comment]
Sounds good. I'll try to make a PR in the coming weeks to integrate with day.js i18n.

**Comment by kenhyuwa** [comment]
Multiple language support, [v1.0.8](https://github.com/kenhyuwa/litepie-datepicker/releases/tag/v1.0.8)
