### ISSUE TITLE
Nuxtjs Support

### ISSUE THREAD

**Issue by swapnilnandgave** [kenhyuwa/litepie-datepicker#20]
I had tried to integrate in nuxtjs but throwing below warnings and not able to work
`Compiled with 29 warnings                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'Fragment' was not found in 'vue'                                                                                       friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'Transition' was not found in 'vue'                                                                                     friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'TransitionGroup' was not found in 'vue'                                                                                friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'computed' was not found in 'vue'                                                                                       friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'createBlock' was not found in 'vue'                                                                                    friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'createCommentVNode' was not found in 'vue'                                                                             friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'createVNode' was not found in 'vue'                                                                                    friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'defineComponent' was not found in 'vue'                                                                                friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'inject' was not found in 'vue'                                                                                         friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'isProxy' was not found in 'vue'                                                                                        friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'mergeProps' was not found in 'vue'                                                                                     friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'nextTick' was not found in 'vue'                                                                                       friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'openBlock' was not found in 'vue'                                                                                      friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'provide' was not found in 'vue'                                                                                        friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'reactive' was not found in 'vue'                                                                                       friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'ref' was not found in 'vue'                                                                                            friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'renderList' was not found in 'vue'                                                                                     friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'renderSlot' was not found in 'vue'                                                                                     friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'resolveComponent' was not found in 'vue'                                                                               friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'resolveDirective' was not found in 'vue'                                                                               friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'toDisplayString' was not found in 'vue'                                                                                friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'unref' was not found in 'vue'                                                                                          friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'vModelText' was not found in 'vue'                                                                                     friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'vShow' was not found in 'vue'                                                                                          friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'watch' was not found in 'vue'                                                                                          friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'watchEffect' was not found in 'vue'                                                                                    friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'withCtx' was not found in 'vue'                                                                                        friendly-errors 16:40:14
                                                                                                                                friendly-errors 16:40:14

 WARN  in ./node_modules/litepie-datepicker/dist/litepie-datepicker.esm.js                                                      friendly-errors 16:40:14

"export 'withDirectives' was not found in 'vue'     `

**Comment by kenhyuwa** [comment]
Hei, Litepie Datepicker only support Vue 3.
nuxt.js still use Vue 2, so please refer to this solution #14 .
