### ISSUE TITLE
manually set the date

### ISSUE THREAD

**Issue by wkiane** [kenhyuwa/litepie-datepicker#21]
I have a search filter and I need to keep the filter state even if the user closes the page, how do I set the date manually? Assuming that I saved it in the session storage for example

**Comment by kenhyuwa** [comment]
Not related issues,
But, you can set state ofter mounted.
```js
setup(){
    const d = ref([])
    
    onMounted(() => {
      // if storage exist
      d.value = localStorage.getItem('date')
    })
  }
```
