### ISSUE TITLE
Invalid date when startDate is outside of endDate month

### ISSUE THREAD

**Issue by matthewbecker1990** [kenhyuwa/litepie-datepicker#22]
Hi,

When setting startDate outside of the endDate month, the datepicker is showing Invalid Date. This issue can be seen on your home page also.

![image](https://user-images.githubusercontent.com/6112221/116966286-2738db00-acf3-11eb-809d-cc2c15b5127f.png)

When opening the date picker and selecting a custom filter, it fixes the issue. When manually selecting a new range, the issue still occurs.

**Comment by kenhyuwa** [comment]
can you give me a specific your problem?

**Comment by kenhyuwa** [comment]
I seen this problem if use multiple props `i18n`,
```vue
<litepie-datepicker i18n="en" />

<litepie-datepicker i18n="id" />
```
