### ISSUE TITLE
Disabling current date

### ISSUE THREAD

**Issue by MariusTechweb** [kenhyuwa/litepie-datepicker#27]
Hello, and awesome library!

I believe there is a bug with disabling current date. If you use `:disable-date `prop to try and disable today, it doesn't work, the date can still be picked.

**Example:**
I set `:disable-date` to disable 22.06.2021 (today), user can still select date.

Looking forward to a response!

**Comment by kenhyuwa** [comment]
yes, today can't be `disabled` for current version.

**Comment by MariusTechweb** [comment]
@kenhyuwa is this a bug or intentional? Kind of weird not to be able to disable today :P

**Comment by kenhyuwa** [comment]
I think this my bad, I fix next release.
Thank you @MariusTechweb
