### ISSUE TITLE
npm run prod issue

### ISSUE THREAD

**Issue by bobking256** [kenhyuwa/litepie-datepicker#29]
When I perform npm run dev on my environment, this component works exactly as expected.  Once I run npm run prod, this component does not display correctly when expanded.  Functionally it works, visually it does not.  The calendar essentially runs vertically down the page (not side by side calendar).  Not sure why that is happening.

**Comment by kenhyuwa** [comment]
please make sure `tailwind.config.js`

```js
module.exports = {
  purge: [
    path.resolve(__dirname, './node_modules/litepie-datepicker/**/*.js')
  ],
}
```
