### ISSUE TITLE
Tailwind 3 support

### ISSUE THREAD

**Issue by ahmedkandel** [kenhyuwa/litepie-datepicker#53]
Hi,

Thanks for the great package,

It there a plan to support Tailwind 3 as i get this error while installing:

```
npm ERR! While resolving: undefined@undefined
npm ERR! Found: tailwindcss@3.0.7
npm ERR! node_modules/tailwindcss
npm ERR!   dev tailwindcss@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tailwindcss@"^2.0.3" from litepie-datepicker@1.0.14
npm ERR! node_modules/litepie-datepicker
npm ERR!   litepie-datepicker@"*" from the root project

```

Thanks.

**Comment by EmilMoe** [comment]
Yep. Rather strange nothing added on this one.

**Comment by syamsoul** [comment]
looks like lately the author seems not so active...

**Comment by EmilMoe** [comment]
I went with this https://vue3datepicker.com

**Comment by elreco** [comment]
You can use it : https://www.npmjs.com/package/litepie-datepicker-tw3 
if you don't want to wait for a @kenhyuwa update :)

**Comment by CrisOspina** [comment]
> You can use it : https://www.npmjs.com/package/litepie-datepicker-tw3 if you don't want to wait for a @kenhyuwa update :)

Hi @elreco,

![image](https://user-images.githubusercontent.com/38017835/152619937-a2bd96d6-eb97-48af-ad8e-2329c618ebf9.png)

Not all CSS is working fine, is it working for you?

**Comment by kawoki** [comment]
@CrisOspina can you share your code?

**Comment by kawoki** [comment]
@CrisOspina can you share your code, package.json, main.js and tailwind.config.js?

**Comment by CrisOspina** [comment]
> @CrisOspina can you share your code, package.json, main.js and tailwind.config.js?

Hi @kawoki 

Yes, code, package.json and tailwind.config

- https://gist.github.com/CrisOspina/3597eb4f911bae42847e567961cc9e4a

**Comment by kawoki** [comment]
@CrisOspina 

```js
content: [
    './index.html',
    './public/**/*.html',
    './src/**/*.{ts,vue}',
    path.resolve(__dirname, './node_modules/litepie-datepicker/**/*.js') // this line here should be litepie-datepicker-tw3
  ],
```

**Comment by CrisOspina** [comment]
> @CrisOspina try editing your `tailwind.config.js`
> 
> ```js
> content: [
>     './index.html',
>     './public/**/*.html',
>     './src/**/*.{ts,vue}',
>     path.resolve(__dirname, './node_modules/litepie-datepicker/**/*.js') // this line here should be litepie-datepicker-tw3
>   ],
> ```

Thanks, it was exactly that, but the css is failing me, the datepicker is positioned on the whole screen

![image](https://user-images.githubusercontent.com/38017835/152811188-c14bea1b-9e94-4a39-98cf-a7c16d3d915c.png)

**Comment by EmilMoe** [comment]
I seem to be missing hover and focus/active styles, any of you experience this?

![image](https://user-images.githubusercontent.com/555083/154841109-b8afb17f-cbbb-4101-a071-45ca98524175.png)

**Comment by EmilMoe** [comment]
> I seem to be missing hover and focus/active styles, any of you experience this?
> 
> ![image](https://user-images.githubusercontent.com/555083/154841109-b8afb17f-cbbb-4101-a071-45ca98524175.png)

Nevermind: https://litepie.com/#configure-with-tailwind

**Comment by lk77** [comment]
For me it does not seems to work

**Comment by brandonleichty** [comment]
It’s a bumber the author created one of the most beautiful date pickers out there and then abandoned maintaining it almost immediately. 😭

**Comment by lk77** [comment]
In the end i used @vuepic/vue-datepicker instead, as i could not make this one work with my custom tailwind theme
