### ISSUE TITLE
How can i call my function ?

### ISSUE THREAD

**Issue by ramkumar201** [kenhyuwa/litepie-datepicker#66]
<litepie-datepicker
      as-single
      :formatter="formatter"
      v-model="values[key]"
      :placeholder="values[key] != '' && !values[na_key] ? values[key] : 'MM-DD-YYYY' "
      class="zI-1"
      readonly="readonly"
      @change="uncheckNa()"
      :key="!values[na_key] ? 1 : 0"
></litepie-datepicker>

Here, If I change date in Datepicker, need to call my js func. I use onChange, but it's not working.

**Comment by FrancoLab** [comment]
Any update on this. Having the same issue

**Comment by FrancoLab** [comment]
@kenhyuwa ^

**Comment by FrancoLab** [comment]
Hi, found a way to do this. Might not be the best way but please let me know if you found an alternative to this.

Basically what happens is the callback function runs when the array is greater than 0. Which you can then use to execute your function.

```javascript
<template>
 <litepie-datepicker
   as-single
   use-range
   :formatter="formatter"
   v-model="dateValue"
 >
 </litepie-datepicker>
</template>
```

```javascript
<script setup>
  import { ref, watch } from "vue";
  import LitepieDatepicker from "litepie-datepicker";
  const dateValue = ref([]);
  const formatter = ref({
      date: 'DD MMM YYYY',
      month: 'MMM'
  });

  watch(dateValue, (val) => {
        if (val.length > 0) {
            console.log(dateValue.value);
        }
  });
</script>
```
