### ISSUE TITLE
Datepicker alignment

### ISSUE THREAD

**Issue by tbordinat** [kenhyuwa/litepie-datepicker#7]
Hi,

Thank you for your work !

As you can see below, the right calendar isn't available, because it's the end of my screen.
![image](https://user-images.githubusercontent.com/4682556/111484284-e92d2b00-8735-11eb-8f20-0456fe894bed.png)

It would be great to be able to define if the div under the label has to be on the left or on right side.
Maybe something like this :
![image](https://user-images.githubusercontent.com/4682556/111484937-7bcdca00-8736-11eb-81af-2fdf5370ee2a.png)

To do so, I simply added a `right-0` here `<div class="absolute z-50 inset-x-auto top-full sm:mt-2.5 right-0"` and set the `right-3` in the `.litepie-datepicker::before` class instead of the `left-3`.

**Comment by kenhyuwa** [comment]
Thank you for suggestions.
for the next, I'll implement with viewports.

**Comment by tbordinat** [comment]
Great ! I don't know viewports but tell me if I can help you in any way.

**Comment by kenhyuwa** [comment]
You can red this [API](https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API).

**Comment by kenhyuwa** [comment]
Fix aligment [v1.0.8](https://github.com/kenhyuwa/litepie-datepicker/releases/tag/v1.0.8).

**Comment by tbordinat** [comment]
I confirm, it's working perfectly, thx a lot !
